### ISSUE TITLE
QA_Geiger Muller Counter_Feedback_smk

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/physical-sciences-iiith#12]
Defect Description :
When we click on the feedback link of "Geiger Muller Counter " experiment, it is redirecting to an error page(404) instead it should redirect to the feedback page.

Actual Result :
When we click on the feedback link of "Geiger Muller Counter " experiment, it is redirecting to an error page(404).

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/physical-sciences-iiith/blob/master/test-cases/integration_test-cases/Geiger%20Muller%20Counter%20/Geiger%20Muller%20Counter%20_12_Feedback_smk.org

Attachment:
![ps24](https://cloud.githubusercontent.com/assets/14869397/14633556/c5175a9a-063b-11e6-803b-6c6498ba092c.png)

**Comment by sadhanareddy** [comment]
Issue is fixed now.

**Comment by sravanthimodepu** [comment]
Issue is fixed. Hence closing the issue.
