### ISSUE TITLE
QA_Geiger Muller Counter_Simulator_p1

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/physical-sciences-iiith#13]
Defect Description :
In the Simulator page of "Geiger Muller Counter " experiment, when we click on the Click here to go to lab link, it is redirecting to a blank page instead a simulation page should get open in-order to perform the simulation process

Actual Result :
In the Simulator page of "Geiger Muller Counter " experiment, when we click on the Click here to go to lab link, it is redirecting to a blank page

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/physical-sciences-iiith/blob/master/test-cases/integration_test-cases/Geiger%20Muller%20Counter%20/Geiger%20Muller%20Counter%20_08_Simulator_p1.org

Attachment:
![ps23](https://cloud.githubusercontent.com/assets/14869397/14633527/a088d780-063b-11e6-9e98-e8b075a7a30a.png)

**Comment by sadhanareddy** [comment]
There is no problem with the simulation. Its not displaying blank page, simulation is getting opened. This simulation runs on Java 3D. I think Java 3D was not properly installed while testing, so it was displaying a blank page.

**Comment by sravanthimodepu** [comment]
Issue is fixed. Hence closing the issue.
