### ISSUE TITLE
QA_Geiger Muller Counter_Procedure_smk

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/physical-sciences-iiith#14]
Defect Description :
In the procedure page of "Geiger Muller Counter " experiment, in the manual video the play button is disabled instead the play button should be enabled in-order to view the video tutorial of manual for the experiment

Actual Result :
In the procedure page of "Geiger Muller Counter " experiment, in the manual video the play button is disabled 

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/physical-sciences-iiith/blob/master/test-cases/integration_test-cases/Geiger%20Muller%20Counter%20/Geiger%20Muller%20Counter%20_05_Procedure_smk.org

Attachment:
![ps22](https://cloud.githubusercontent.com/assets/14869397/14633498/818492a2-063b-11e6-9259-6ab9f96a4825.png)

**Comment by sadhanareddy** [comment]
Manual video was not enabled because, link to this image was not given. i.e., .swf file to run this video was not given, only the manual image is given without a link. Hence commented out this image as .swf file was not found.

**Comment by sravanthimodepu** [comment]
Issue is fixed. Hence closing the issue.
