### ISSUE TITLE
QA_Heat of Neutralization_Feedback_smk

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/physical-sciences-iiith#19]
Defect Description :
When we click on the feedback link of "Heat of Neutralization " experiment, it is redirecting to an error page(404) instead it should redirect to the feedback page.

Actual Result :
When we click on the feedback link of "Heat of Neutralization " experiment, it is redirecting to an error page(404).

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/physical-sciences-iiith/blob/master/test-cases/integration_test-cases/Heat%20of%20Neutralization%20/Heat%20of%20Neutralization%20_13_Feedback_smk.org

Attachment:
![ps17](https://cloud.githubusercontent.com/assets/14869397/14633261/7593f72c-063a-11e6-9358-e309bcd3089b.png)

**Comment by sadhanareddy** [comment]
Issue is fixed now.

**Comment by sravanthimodepu** [comment]
Issue is fixed. Hence closing the issue.
