### ISSUE TITLE
QA_Inversion of Cane Sugar_Theory_smk

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/physical-sciences-iiith#2]
Defect Description :
In the Theory page of "Inversion of Cane Sugar " experiment, Content is present with distortions and Junk characters instead the alignment of the data should be clear in-order to maintain the page utility

Actual Result :
In the Theory page of "Inversion of Cane Sugar " experiment, Content is present with distortions and Junk characters

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/physical-sciences-iiith/blob/master/test-cases/integration_test-cases/Inversion%20of%20Cane%20Sugar%20/Inversion%20of%20Cane%20Sugar%20_07_Theory_smk.org

Attachment:
![ps34](https://cloud.githubusercontent.com/assets/14869397/14633935/77c2f626-063d-11e6-9a58-37ab990bce4b.png)

**Comment by sadhanareddy** [comment]
Issue is fixed now.

**Comment by sadhanareddy** [comment]
Issue is fixed. Content distortions, junk characters and alignment of the data in theory page is been fixed. Now the content looks clear with no distortions.

**Comment by sravanthimodepu** [comment]
Issue is fixed. Hence closing the issue.
