### ISSUE TITLE
QA_Inversion of Cane Sugar_Prerequisites_p1

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/physical-sciences-iiith#21]
Defect Description :
In the "Inversion of Cane Sugar " experiment, the minimum requirement to run the experiment is not displayed in the page instead a page or Scrolling should appear providing information on minimum requirement to run this experiment, information like Bandwidth,Device Resolution,Hardware Configuration and Software Required.

Actual Result :
In the "Inversion of Cane Sugar " experiment, the minimum requirement to run the experiment is not displayed in the page.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/physical-sciences-iiith/blob/master/test-cases/integration_test-cases/Inversion%20of%20Cane%20Sugar%20/Inversion%20of%20Cane%20Sugar%20_18_Back%20to%20experiments_smk.org

Attachment:
![inversion of cs](https://cloud.githubusercontent.com/assets/14869397/14633184/1e02addc-063a-11e6-81cc-748a532f2250.png)

**Comment by sadhanareddy** [comment]
Issue is fixed now. Client side dependencies to run the simulation are given in prerequisites tab.

**Comment by sravanthimodepu** [comment]
Issue is fixed. Hence closing the issue.
