### ISSUE TITLE
QA_Inversion of Cane Sugar_Feedback_smk

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/physical-sciences-iiith#22]
Defect Description :
When we click on the feedback link of "Inversion of Cane Sugar " experiment, it is redirecting to an error page(404) instead it should redirect to the feedback page.

Actual Result :
When we click on the feedback link of "Inversion of Cane Sugar " experiment, it is redirecting to an error page(404).

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/physical-sciences-iiith/blob/master/test-cases/integration_test-cases/Inversion%20of%20Cane%20Sugar%20/Inversion%20of%20Cane%20Sugar%20_16_Feedback_smk.org

Attachment:
![ps14](https://cloud.githubusercontent.com/assets/14869397/14633058/6a929618-0639-11e6-9a38-f0b9923cc737.png)

**Comment by sadhanareddy** [comment]
Issue is fixed now.

**Comment by sravanthimodepu** [comment]
Issue is fixed. Hence closing the issue.
