### ISSUE TITLE
QA_Photoelectric Effect_Back to experiment_smk

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/physical-sciences-iiith#25]
Defect Description :
In the "Photoelectric Effect " experiment,the back to experiments link is not present in the page instead the back to experiments link should be displayed on the screen in-order to view the list of experiments by the user.

Actual Result :
In the "Photoelectric Effect" experiment,the back to experiments link is not present in the page.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/physical-sciences-iiith/blob/master/test-cases/integration_test-cases/Photoelectric%20Effect/Photoelectric%20Effect_12_Back%20to%20experiment_smk.org

Attachment:
![ps11](https://cloud.githubusercontent.com/assets/14869397/14632888/a057c0ee-0638-11e6-853c-e3b8918436da.png)

**Comment by sadhanareddy** [comment]
Issue is fixed now.

**Comment by sravanthimodepu** [comment]
Issue is fixed. Hence closing the issue.
