### ISSUE TITLE
QA_Photoelectric Effect_Usability_smk

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/physical-sciences-iiith#27]
Defect Description :
In the Introduction page of "Photoelectric Effect " experiment ,the Quiz and References data are displaying at the bottom of the page instead the Quiz and References should be placed as headers with different pages

Actual Result :
In the Introduction page of "Photoelectric Effect " experiment ,the Quiz and References data are displaying at the bottom of the page

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/physical-sciences-iiith/blob/master/test-cases/integration_test-cases/Photoelectric%20Effect/Photoelectric%20Effect_01_Usability_smk.org

Attachment:
![ps9](https://cloud.githubusercontent.com/assets/14869397/14632840/521ab846-0638-11e6-9f7d-22c443808ecf.png)

**Comment by sadhanareddy** [comment]
Issue is fixed now.

**Comment by sravanthimodepu** [comment]
Issue is fixed. Hence closing the issue.
