### ISSUE TITLE
QA_Photoelectric Effect_Theory_smk

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/physical-sciences-iiith#3]
Defect Description :
In the Theory page of "Photoelectric Effect " experiment, Content is present with distortions and Junk characters instead the alignment of the data should be clear in-order to maintain the page utility

Actual Result :
In the Theory page of "Photoelectric Effect " experiment, Content is present with distortions and Junk characters

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/physical-sciences-iiith/blob/master/test-cases/integration_test-cases/Photoelectric%20Effect/Photoelectric%20Effect_04_Theory_smk.org

Attachment:
![ps33](https://cloud.githubusercontent.com/assets/14869397/14633911/5e2f3422-063d-11e6-865a-8e3a32f991b3.png)

**Comment by sadhanareddy** [comment]
Issue is fixed now.

**Comment by sadhanareddy** [comment]
Issue is fixed. Content distortions, junk characters and alignment of the data in theory page is been fixed. Now the content looks clear with no distortions.

**Comment by sravanthimodepu** [comment]
Issue is fixed. Hence closing the issue.
