### ISSUE TITLE
QA_Millikans Experiment_Simulator_p1

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/physical-sciences-iiith#30]
Defect Description :
In the Simulator page of "Millikans Experiment " experiment, when we click on the Virtual Lab link, it is redirecting to a blank page instead a simulation page should get open in-order to perform the simulation process

Actual Result :
In the Simulator page of "Millikans Experiment " experiment, when we click on the Virtual Lab link, it is redirecting to a blank page

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/physical-sciences-iiith/blob/master/test-cases/integration_test-cases/Millikan%27s%20Experiment%20/Millikan%27s%20Experiment%20_08_Simulator_p1.org

Attachment:
![ps6](https://cloud.githubusercontent.com/assets/14869397/14631113/75eec450-062f-11e6-82c9-0b8adf14ab5e.png)

**Comment by sadhanareddy** [comment]
There is no problem with the simulation. Its not displaying blank page, simulation is getting opened. This simulation runs on Java 3D. I think Java 3D was not properly installed while testing, so it was displaying a blank page.

**Comment by sravanthimodepu** [comment]
Issue is fixed. Hence closing the issue.
