### ISSUE TITLE
QA_Measurement of Dipole Moment_Feedback_smk

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/physical-sciences-iiith#32]
Defect Description :
When we click on the feedback link of Measurement of Dipole Moment" experiment, it is redirecting to an error page(404) instead it should redirect to the feedback page. 

Actual Result :
When we click on the feedback link of Measurement of Dipole Moment" experiment, it is redirecting to an error page(404).

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/physical-sciences-iiith/blob/master/test-cases/integration_test-cases/Measurement%20of%20Dipole%20Moment%20/Measurement%20of%20Dipole%20Moment%20_13_Feedback_smk.org

Attachment:
![ps4](https://cloud.githubusercontent.com/assets/14869397/14631072/3498369e-062f-11e6-9a9b-ed65220ed83e.png)

**Comment by sadhanareddy** [comment]
Issue is fixed now.

**Comment by sravanthimodepu** [comment]
Issue is fixed. Hence closing the issue.
