### ISSUE TITLE
QA_Measurement of Dipole Moment_Objective_smk

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/physical-sciences-iiith#34]
Defect Description :
In the Objective page of "Measurement of Dipole Moment " experiment, the alignment of the text is not clear instead the data should be present within the page 

Actual Result :
In the Objective page of "Measurement of Dipole Moment " experiment, the alignment of the text is not clear

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/physical-sciences-iiith/blob/master/test-cases/integration_test-cases/Measurement%20of%20Dipole%20Moment%20/Measurement%20of%20Dipole%20Moment%20_03_Objective_smk.org

Attachment:
![ps2](https://cloud.githubusercontent.com/assets/14869397/14631021/dea72b82-062e-11e6-8351-08e7887426ee.png)

**Comment by sadhanareddy** [comment]
Issue is fixed now.

**Comment by sravanthimodepu** [comment]
Issue is fixed. Hence closing the issue.
