### ISSUE TITLE
QA_Physical Science Virtual_Feedback_smk

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/physical-sciences-iiith#35]
Defect Description :
In the home page of "Physical Science Virtual" Lab,when we click on the feedback link it is redirecting to an error page(404) instead feedback page should get opened.

Actual Result :
In the home page of "Physical Science Virtual" Lab,when we click on the feedback link it is redirecting to an error page(404).

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/physical-sciences-iiith/blob/master/test-cases/integration_test-cases/System/Physical%20Science%20Virtual%20Labs%20l_07_Feedback_smk.org

Attachment:
![ps1](https://cloud.githubusercontent.com/assets/14869397/14630766/4743b3e2-062d-11e6-99e3-3557a2d8a282.png)

**Comment by sadhanareddy** [comment]
Issue is fixed now.

**Comment by sravanthimodepu** [comment]
Issue is fixed. Hence closing the issue.
