### ISSUE TITLE
QA_Millikans Experiment_Theory_smk

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/physical-sciences-iiith#4]
Defect Description :
In the Theory page of "Millikans Experiment " experiment, Content is present with distortions and Junk characters instead the alignment of the data should be clear in-order to maintain the page utility

Actual Result :
In the Theory page of "Millikans Experiment " experiment, Content is present with distortions and Junk characters

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/physical-sciences-iiith/blob/master/test-cases/integration_test-cases/Millikan%27s%20Experiment%20/Millikan%27s%20Experiment%20_04_Theory_smk.org

Attachment:
![ps32](https://cloud.githubusercontent.com/assets/14869397/14633882/424b4836-063d-11e6-8119-e14ce2ca6e53.png)

**Comment by sadhanareddy** [comment]
Issue is fixed now.

**Comment by sadhanareddy** [comment]
Issue is fixed. Content distortions, junk characters and alignment of the data in theory page is been fixed. Now the content looks clear with no distortions.

**Comment by sravanthimodepu** [comment]
Issue is fixed. Hence closing the issue.
