### ISSUE TITLE
QA_Surface Tension_Simulator_smk

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/physical-sciences-iiith#7]
Defect Description :
In the Simulator page of "Surface Tension" experiment, when we click on the “Click here to go to lab” link, it is redirecting to a blank page instead a simulation page should get open in-order to perform the simulation process

Actual Result :
In the Simulator page of "Surface Tension" experiment, when we click on the “Click here to go to lab” link, it is redirecting to a blank page

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/physical-sciences-iiith/blob/master/test-cases/integration_test-cases/Surface%20Tension%20/Surface%20Tension%20_07_Simulator_smk.org

Attachment:
![ps29](https://cloud.githubusercontent.com/assets/14869397/14633687/626d9c0a-063c-11e6-9cb0-795d97855db3.png)

**Comment by sadhanareddy** [comment]
There is no problem with the simulation. Its not displaying blank page, simulation is getting opened. This simulation runs on Java 3D. I think Java 3D was not properly installed while testing, so it was displaying a blank page.

**Comment by sravanthimodepu** [comment]
Issue is fixed. Hence closing the issue.
