### ISSUE TITLE
QA_Youngs Modulus_Prerequisites_p1

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/physical-sciences-iiith#8]
Defect Description :
In the "Young’s Modulus  " experiment, the minimum requirement to run the experiment is not displayed in the page instead a page or Scrolling should appear providing information on minimum requirement to run this experiment, information like Bandwidth,Device Resolution,Hardware Configuration and Software Required.

Actual Result :
In the "Young’s Modulus  " experiment, the minimum requirement to run the experiment is not displayed in the page.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/physical-sciences-iiith/blob/master/test-cases/integration_test-cases/Young%27s%20Modulus%20/Young%27s%20Modulus%20_15_Prerequisites_p1.org

Attachment:
![young](https://cloud.githubusercontent.com/assets/14869397/14633670/4d01d052-063c-11e6-946d-66151df3a35d.png)

**Comment by sadhanareddy** [comment]
Issue is fixed now. Client side dependencies to run the simulation are given in prerequisites tab.

**Comment by sravanthimodepu** [comment]
Issue is fixed. Hence closing the issue.
