### ISSUE TITLE
QA_Youngs Modulus_Feedback_smk

### ISSUE THREAD

**Issue by kolliSuman** [Virtual-Labs/physical-sciences-iiith#9]
Defect Description :
When we click on the feedback link of "Youngs Modulus  " experiment, it is redirecting to an error page(404) instead it should redirect to the feedback page.

Actual Result :
When we click on the feedback link of "Youngs Modulus  " experiment, it is redirecting to an error page(404).

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/physical-sciences-iiith/blob/master/test-cases/integration_test-cases/Young%27s%20Modulus%20/Young%27s%20Modulus%20_12_Feedback_smk.org

Attachment:
![ps27](https://cloud.githubusercontent.com/assets/14869397/14633611/0c262cb8-063c-11e6-9c13-2acb417c2240.png)

**Comment by sadhanareddy** [comment]
Issue is fixed now.

**Comment by sravanthimodepu** [comment]
Issue is fixed. Hence closing the issue.
